language: python

python:
  - 2.7

env:
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=docs-py3

before_install:
  - export EASY_SETUP_URL='http://peak.telecommunity.com/dist/ez_setup.py'

install:
  - pip install --use-mirrors tox

script:
  - tox -e $TOX_ENV

  